---
# Aminator playbook for Amazon Linux
- name: Aminator
  user: ec2-user
  sudo: True
  tags: aminator
  hosts: all
  roles:
    - base
    - aminator
  vars_files:
    - vars/$ansible_distribution.yml
  
